export enum AppContainer {
  EMAIL_PROVIDER = 'EMAIL_PROVIDER',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION_PROVIDER',
  MAIL_LIST_PROVIDER = 'MAIL_LIST_PROVIDER',
  SMS_PROVIDER = 'SMS_PROVIDER',
  WHATSAPP_PROVIDER = 'WHATSAPP_PROVIDER',
}
